name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.RASPBERRY_HOST }}
        username: ${{ secrets.RASPBERRY_USER }}
        key: ${{ secrets.RASPBERRY_SSH_KEY }}
        port: ${{ secrets.RASPBERRY_PORT || 22 }}
        script: |
          echo "Starting backend deployment..."
          cd /home/y0rshb3/devops/temp_backend
          
          echo "Pulling latest changes..."
          git pull origin main
          
          echo "Restoring environment variables..."
          cat > .env << ENVEOF
          portListen=${{ secrets.PORT }}
          hostDatabase=${{ secrets.DB_HOST }}
          userDatabase=${{ secrets.DB_USER }}
          passwordDatabase=${{ secrets.DB_PASSWORD }}
          database=${{ secrets.DB_NAME }}
          ENVEOF
          
          echo "Installing dependencies..."
          npm install
          
          echo "Restarting backend container..."
          docker restart backend
          
          echo "Waiting for backend to start..."
          sleep 5
          
          echo "Testing backend health..."
          curl -f http://localhost:4000/api/v1/info/home && echo "Backend is healthy!" || echo "Backend health check failed"
          
          echo "Backend deployed successfully!"
